import { Heading } from '@/components/heading'
import { Button } from '@/components/ui/button'
import { MaxWidthContainer } from '@/components/ui/max-width-container'
import { Metadata } from 'next'
import Link from 'next/link'
import { OffersList } from './_components/offers-list'
import { SubHeading } from '@/components/sub-heading'
import { Text } from '@/components/ui/text'
import { StoryAlbum } from './_components/story-album'
import { CoursesList } from './_components/courses-list'
import { FAQList } from './_components/faq-list'
import { Separator } from '@/components/ui/separator'
import { ArrowRight, ArrowUpRight, Headphones } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Toothache | Melhor instituto de dentistas',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      {/* Hero */}
      <div className="hero-img flex items-center sm:pt-16 bg-no-repeat bg-center bg-fixed md:min-h-screen sm:text-left">
        <MaxWidthContainer>
          <div className="z-10 mt-16 sm:mt-0 w-full md:max-w-2xl flex flex-col justify-center ">
            {/* Title */}
            <h1 className="text-primary-foreground font-semibold m-0 text-4xl md:text-4xl mb-6 break-words">
              Excelência, Pessoalidade e Modernidade.
            </h1>

            <p className="text-primary-foreground font-medium text-lg mb-16">
              Estes são os pilares do nosso negócio, tratamos cada cliente de
              forma personalizada, promovendo um atendimento célere, eficiente e
              humanizado gerando valor para nossos clientes.
            </p>

            <div className="flex flex-col md:flex-row gap-3">
              <Link
                href="/relatos"
                prefetch={false}
                className="flex justify-center"
              >
                <Button color="primary" className="w-full text-base">
                  Soluções
                </Button>
              </Link>
              <Link
                href="/contato"
                prefetch={false}
                className="flex justify-center"
              >
                <Button color="secondary" className="w-full text-base">
                  Entre em contato
                </Button>
              </Link>
            </div>
          </div>
        </MaxWidthContainer>
      </div>

      {/* Why to choose */}
      <MaxWidthContainer>
        <div>
          <SubHeading content="Nosso melhor" className="text-center" />
          <Heading content="O que oferecemos" className="text-center" />
        </div>
        <div className="mt-8">
          <OffersList />
        </div>
      </MaxWidthContainer>

      {/* Story */}
      <div className="border-y border-border bg-muted flex items-center justify-center">
        <MaxWidthContainer className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="space-y-6">
            <div>
              <SubHeading content="Um pouco da caminhada" />
              <Heading content="Nossa História" />
            </div>

            <div className="space-y-4">
              <Text>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Asperiores hic magnam odio est aliquid earum? Quod est impedit
                perspiciatis accusamus fugiat, dolor repellendus neque, modi,
                cupiditate fuga natus praesentium. Debitis.
              </Text>

              <Text>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Asperiores hic magnam odio est aliquid earum? Quod est impedit
                perspiciatis accusamus fugiat, dolor repellendus neque, modi,
                cupiditate fuga natus praesentium. Debitis.
              </Text>
            </div>
          </div>

          <div>
            <StoryAlbum />
          </div>
        </MaxWidthContainer>
      </div>

      {/* Courses */}
      <MaxWidthContainer className="space-y-6">
        <div>
          <SubHeading content="Os melhores cursos" />
          <Heading content="Cursos" />
        </div>

        <div>
          <CoursesList />
        </div>
      </MaxWidthContainer>

      {/* Depositions */}
      <MaxWidthContainer>relatos</MaxWidthContainer>

      {/* Frequently asked questions */}
      <MaxWidthContainer className="space-y-16">
        <Separator />

        <div className="space-y-16">
          <div className="space-y-8 max-w-2xl mx-auto w-full">
            <div>
              <Heading
                content="Ficou com dúvidas? Não se preocupe"
                className="text-center"
              />
            </div>

            <div>
              <FAQList />
            </div>
          </div>

          <div className="bg-muted p-8 border rounded-md">
            <div className="max-w-2xl mx-auto w-full flex flex-col items-center text-center">
              <Headphones className="text-primary w-8 h-8" />

              <h3 className="text-2xl font-semibold mb-6">Entre em contato</h3>

              <p className="text-muted-foreground text-base mb-8 leading-normal">
                Estamos aqui para ajudar. Entre em contato para suporte técnico
                personalizado em nossos produtos e serviços.
              </p>

              <div className="flex flex-col md:flex-row md:justify-center gap-4 w-full">
                <Link prefetch={false} href="/">
                  <Button variant="outline">
                    WhatsApp <ArrowUpRight className="h-4 w-4" />
                  </Button>
                </Link>

                <Link prefetch={false} href="/">
                  <Button>
                    Fale Conosco <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>

        <Separator />
      </MaxWidthContainer>

      {/* CTA */}
      <MaxWidthContainer></MaxWidthContainer>
    </main>
  )
}
