/**
 * External
 */
import { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Headphones } from 'lucide-react'

/**
 * Internal
 */
import { Heading } from '@/components/heading'
import { Button } from '@/components/ui/button'
import { MaxWidthContainer } from '@/components/ui/max-width-container'
import { OffersList } from './_components/offers-list'
import { SubHeading } from '@/components/sub-heading'
import { Text } from '@/components/ui/text'
import { StoryAlbum } from './_components/story-album'
import { CoursesList } from './_components/courses-list'
import { FAQList } from './_components/faq-list'
import { ContactOptions } from './_components/contact-options'
import { ContentFrame } from './_components/content-frame'
import { ImagesMosaic } from './_components/images-mosaic'
import { TestimonialsList } from './_components/testimonials-list'
import { Separator } from '@/components/ui/separator'
import { whatsappLink } from '@/site'

export const metadata: Metadata = {
  title: 'Toothache | Melhor instituto de dentistas',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      {/* Hero */}
      <div
        id="hero"
        className="hero-img flex items-center sm:pt-16 bg-no-repeat bg-center bg-fixed md:min-h-screen sm:text-left"
      >
        <MaxWidthContainer>
          <div className="z-10 mt-16 sm:mt-0 w-full md:max-w-2xl flex flex-col justify-center ">
            {/* Title */}
            <h1 className="text-primary-foreground font-semibold m-0 text-4xl md:text-4xl mb-6 break-words">
              Excelência, Pessoalidade e Modernidade.
            </h1>

            <p className="text-primary-foreground font-medium text-lg mb-16">
              Estes são os pilares do nosso negócio, tratamos cada cliente de
              forma personalizada, promovendo um atendimento célere, eficiente e
              humanizado gerando valor para nossos clientes.
            </p>

            <div className="flex flex-col md:flex-row gap-3">
              <Link
                href="/relatos"
                prefetch={false}
                className="flex justify-center"
              >
                <Button variant="outline" className="w-full text-base">
                  Cursos
                </Button>
              </Link>
              <Link
                href="/contato"
                prefetch={false}
                className="flex justify-center"
              >
                <Button className="w-full text-base">Entre em contato</Button>
              </Link>
            </div>
          </div>
        </MaxWidthContainer>
      </div>

      {/* Why to choose */}
      <MaxWidthContainer id="o-que-oferecemos">
        <div>
          <SubHeading content="Nosso melhor" className="text-center" />
          <Heading content="O que oferecemos" className="text-center" />
        </div>
        <div className="mt-8">
          <OffersList />
        </div>
      </MaxWidthContainer>

      {/* Story */}
      <div className="border-y border-border bg-muted flex items-center justify-center">
        <MaxWidthContainer
          className="grid grid-cols-1 lg:grid-cols-2 gap-8"
          id="historia"
        >
          <div className="space-y-6">
            <div>
              <SubHeading content="Um pouco da caminhada" />
              <Heading content="Nossa História" />
            </div>

            <div className="space-y-4">
              <Text>
                O Instituto Líder iniciou suas atividades no ano de 2004, com o
                intuito de difundir uma nova filosofia de ensino nas mais
                diversas especialidades odontológicas. Com uma visão
                multidisciplinar, utilizando-se de técnicas inovadoras,
                materiais de última geração e um corpo clínico formado por
                mestres e doutores, tornou-se referência no segmento de
                pós-graduação na Bahia.
              </Text>

              <Text>
                Nosso instituto encontra-se localizado no bairro do Rio
                Vermelho, em sede própria, com excelente localização e fácil
                estacionamento. Dotada de ampla estrutura, composta por salas de
                aulas climatizadas, clínica com 12 consultórios, ampla recepção,
                sala de Rx, sala de esterilização e laboratório de prótese.
                Somado a isso, temos um amplo corpo técnico-administrativo,
                treinado para melhor atendê-lo (a).
              </Text>
            </div>
          </div>

          <div>
            <StoryAlbum />
          </div>
        </MaxWidthContainer>
      </div>

      {/* Courses */}
      <MaxWidthContainer id="cursos" className="space-y-6">
        <div>
          <SubHeading content="Os melhores cursos" />
          <Heading content="Conheça nossas formações" />
        </div>

        <div>
          <CoursesList />
        </div>
      </MaxWidthContainer>

      {/* Testimonial */}
      <MaxWidthContainer id="relatos">
        <div className="space-y-6">
          <div className=" mx-auto w-full">
            <SubHeading content="Venha ser o próximo" />
            <Heading content="Eles conquistaram seus objetivos de carreira e transformaram suas vidas" />
          </div>

          <div>
            <TestimonialsList />
          </div>
        </div>
      </MaxWidthContainer>

      {/* Frequently asked questions */}
      <MaxWidthContainer>
        <ContentFrame>
          <div className="space-y-16">
            <div className="space-y-8 max-w-2xl mx-auto w-full">
              <div>
                <Heading
                  content="Ficou com dúvidas? Não se preocupe"
                  className="text-center"
                />
              </div>

              <div>
                <FAQList />
              </div>
            </div>

            <div className="bg-muted p-8 border rounded-md">
              <div className="max-w-2xl mx-auto w-full flex flex-col items-center text-center">
                <Headphones className="text-primary w-8 h-8 mb-3" />

                <h3 className="text-2xl font-semibold mb-6">
                  Entre em contato
                </h3>

                <p className="text-muted-foreground text-base mb-8 leading-normal">
                  Estamos aqui para ajudar. Entre em contato para suporte
                  técnico personalizado em nossos produtos e serviços.
                </p>

                <div className="flex flex-col md:flex-row md:justify-center gap-4 w-full">
                  <Link
                    prefetch={false}
                    href={whatsappLink}
                    target="_blank"
                    className="w-full md:w-fit"
                  >
                    <Button variant="outline" className="w-full md:w-fit">
                      WhatsApp <ArrowUpRight className="h-4 w-4" />
                    </Button>
                  </Link>

                  <Link
                    prefetch={false}
                    href="#contato"
                    className="w-full md:w-fit"
                  >
                    <Button className="w-full md:w-fit">
                      Fale Conosco <ArrowRight className="h-4 w-4" />
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </ContentFrame>
      </MaxWidthContainer>

      {/* CTA */}
      <MaxWidthContainer
        id="contato"
        className="grid grid-cols-1 md:grid-cols-2 gap-12"
      >
        <div className="flex flex-col justify-center">
          <div>
            <SubHeading content="Seja nosso aluno" />
            <Heading content="Venha se profissionalizar com a gente" />
          </div>

          <div className="mt-8 mb-4 flex flex-col gap-4">
            <Separator />
            <ContactOptions />
            <Separator />
          </div>

          <div className="flex flex-col">
            <p className="mt-4 text-muted-foreground leading-relaxed text-sm">
              Mande uma mensagem para nossa equipe para ingressar nos nossos
              cursos.
            </p>

            <Link prefetch={false} href={whatsappLink}>
              <Button className="w-full md:w-fit mt-4">Começar agora</Button>
            </Link>
          </div>
        </div>

        <div>
          <ImagesMosaic />
        </div>
      </MaxWidthContainer>
    </main>
  )
}
