import { Heading } from '@/components/heading'
import { Button } from '@/components/ui/button'
import { MaxWidthContainer } from '@/components/ui/max-width-container'
import { Metadata } from 'next'
import Link from 'next/link'
import { OffersList } from './_components/offers-list'

export const metadata: Metadata = {
  title: 'Toothache | Melhor instituto de dentistas',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      {/* Hero */}
      <div className="hero-img flex items-center sm:pt-16 bg-no-repeat bg-center bg-fixed md:min-h-screen sm:text-left">
        <MaxWidthContainer>
          <div className="z-10 mt-16 sm:mt-0 w-full md:max-w-2xl flex flex-col justify-center ">
            {/* Title */}
            <h1 className="text-primary-foreground font-semibold m-0 text-4xl md:text-4xl mb-6 break-words">
              Excelência, Pessoalidade e Modernidade.
            </h1>

            <p className="text-primary-foreground font-medium text-lg mb-16">
              Estes são os pilares do nosso negócio, tratamos cada cliente de
              forma personalizada, promovendo um atendimento célere, eficiente e
              humanizado gerando valor para nossos clientes.
            </p>

            <div className="flex flex-col md:flex-row gap-3">
              <Link
                href="/relatos"
                prefetch={false}
                className="flex justify-center"
              >
                <Button color="primary" className="w-full text-base">
                  Soluções
                </Button>
              </Link>
              <Link
                href="/contato"
                prefetch={false}
                className="flex justify-center"
              >
                <Button color="secondary" className="w-full text-base">
                  Entre em contato
                </Button>
              </Link>
            </div>
          </div>
        </MaxWidthContainer>
      </div>

      {/* Why to choose */}
      <MaxWidthContainer>
        <Heading content="O que oferecemos" className="text-center" />

        <div className="mt-8">
          <OffersList />
        </div>
      </MaxWidthContainer>

      {/* Story */}

      {/* Courses */}

      {/* Depositions */}

      {/* Frequently asked questions */}

      {/* CTA */}
    </main>
  )
}
