import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@/styles/globals.css'
import { ContactWidget } from '@/components/contact-widget'
import { MenuContextProvider } from '@/contexts/menu-context'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MenuContextProvider>
        <body
          className={`${montserrat.className} min-h-screen antialiased bg-background text-foreground scroll-smooth`}
        >
          {children}
          <ContactWidget />
        </body>
      </MenuContextProvider>
    </html>
  )
}
